- name: loops
  hosts: local
  connection: local
  tasks:
  - name: Installing Packages
    ansible.builtin.service:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - mysql
    - zip